<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite errors="0" failures="0" tests="4" skipped="0" name=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_fetchSession" timestamp="2020-12-22T23:23:54">
    <properties>
      <property name="platform" value="vm"/>
    </properties>
    <testcase classname=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_fetchSession" name="fetchSession request returns a AuthCognitoSession" time="0.051"/>
    <testcase classname=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_fetchSession" name="fetchSession thrown PlatFormException results in AuthError" time="0.012"/>
    <testcase classname=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_fetchSession" name="CognitoAuthSession handles null tokens" time="0.007"/>
    <testcase classname=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_fetchSession" name="CognitoAuthSession handles tokens" time="0.006"/>
  </testsuite>
  <testsuite errors="0" failures="0" tests="1" skipped="0" name=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_signOut" timestamp="2020-12-22T23:23:54">
    <properties>
      <property name="platform" value="vm"/>
    </properties>
    <testcase classname=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_signOut" name="signUp request returns a SignOutResult" time="0.047"/>
  </testsuite>
  <testsuite errors="0" failures="0" tests="2" skipped="0" name=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_getCurrentUser" timestamp="2020-12-22T23:23:54">
    <properties>
      <property name="platform" value="vm"/>
    </properties>
    <testcase classname=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_getCurrentUser" name="getCurrentUser request returns an AuthUser" time="0.059"/>
    <testcase classname=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_getCurrentUser" name="PlatformException in getCurrentUser surfaces as AuthError" time="0.028"/>
  </testsuite>
  <testsuite errors="0" failures="0" tests="2" skipped="0" name=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_confirmSignIn" timestamp="2020-12-22T23:23:54">
    <properties>
      <property name="platform" value="vm"/>
    </properties>
    <testcase classname=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_confirmSignIn" name="confirmSignIn request returns a SignInResult" time="0.068"/>
    <testcase classname=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_confirmSignIn" name="signIn thrown PlatFormException results in AuthError" time="0.014"/>
  </testsuite>
  <testsuite errors="0" failures="0" tests="1" skipped="0" name=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_confirmPassword" timestamp="2020-12-22T23:23:54">
    <properties>
      <property name="platform" value="vm"/>
    </properties>
    <testcase classname=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_confirmPassword" name="confirmPassword request returns a UpdatePasswordResult" time="0.055"/>
  </testsuite>
  <testsuite errors="0" failures="0" tests="1" skipped="0" name=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_confirmSignup" timestamp="2020-12-22T23:23:54">
    <properties>
      <property name="platform" value="vm"/>
    </properties>
    <testcase classname=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_confirmSignup" name="confirmnSignUp request returns a SignUpResult" time="0.057"/>
  </testsuite>
  <testsuite errors="0" failures="0" tests="1" skipped="0" name=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_resendSignUpCode" timestamp="2020-12-22T23:23:54">
    <properties>
      <property name="platform" value="vm"/>
    </properties>
    <testcase classname=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_resendSignUpCode" name="resendSignUpCode request returns a ResendSignUpCodeResult" time="0.048"/>
  </testsuite>
  <testsuite errors="0" failures="0" tests="3" skipped="0" name=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_signup" timestamp="2020-12-22T23:23:54">
    <properties>
      <property name="platform" value="vm"/>
    </properties>
    <testcase classname=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_signup" name="signUp request returns a CognitoSignUpResult" time="0.053"/>
    <testcase classname=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_signup" name="signUp request nextStep casts to AuthNextSignUpStep and AuthNextStep" time="0.007"/>
    <testcase classname=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_signup" name="signUp thrown PlatFormException results in AuthError" time="0.012"/>
  </testsuite>
  <testsuite errors="0" failures="0" tests="1" skipped="0" name=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_resetPassword" timestamp="2020-12-22T23:23:54">
    <properties>
      <property name="platform" value="vm"/>
    </properties>
    <testcase classname=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_resetPassword" name="resetPassword request returns a ResetPasswordResult" time="0.046"/>
  </testsuite>
  <testsuite errors="0" failures="0" tests="1" skipped="0" name=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_updatePassword" timestamp="2020-12-22T23:23:54">
    <properties>
      <property name="platform" value="vm"/>
    </properties>
    <testcase classname=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_updatePassword" name="updatePassword request returns a UpdatePasswordResult" time="0.037"/>
  </testsuite>
  <testsuite errors="0" failures="0" tests="3" skipped="0" name=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_signin" timestamp="2020-12-22T23:23:54">
    <properties>
      <property name="platform" value="vm"/>
    </properties>
    <testcase classname=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_signin" name="signUp request returns a SignInResult" time="0.04"/>
    <testcase classname=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_signin" name="signIn request nextStep casts to AuthNextSignStep and AuthNextStep" time="0.004"/>
    <testcase classname=".Users.pravgupt.Workspaces.Flutter.amplify_fork.amplify_flutter.packages.amplify_auth_cognito.test.amplify_auth_cognito_signin" name="signIn thrown PlatFormException results in AuthError" time="0.007"/>
  </testsuite>
</testsuites>